export const mockData = [
  {
    uid: "8fbfbe6a95d244bfb0dd7f730ca0e515",
    picUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    firstName: "Will",
    lastName: "Byers",
    city: "Chicago",
    state: "IL",
    preferredCodingTime: ["morning", "afternoon", "evening"],
    frontendTechStack: [
      "HTML",
      "CSS",
      "Javascript",
      "jQuery",
      "React",
      "Angular",
      "Vue",
    ],
    backendTechStack: [
      "Linux",
      "Apache",
      "MongoDB",
      "Express.JS",
      "Node.js",
      "SQLite",
      "Python",
    ],
    specialty: ["Full-Stack"],
    preferredTechStack: ["HTML", "CSS", "Javascript", "Angular", "Java"],
    bio:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    uid: "854f28eca5994947896e636f99ae",
    picUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    firstName: "Kimberly",
    lastName: "Montgomery",
    city: "Phoenix",
    state: "AR",
    preferredCodingTime: ["morning", "evening"],
    frontendTechStack: ["HTML", "CSS", "Vue"],
    backendTechStack: ["Linux", "Node.js", "Javascript"],
    specialty: ["Back-End"],
    preferredTechStack: ["HTML", "CSS", "Javascript", "React"],
    bio: "Fringilla phasellus faucibus scelerisque eleifend donec pretium.",
  },
  {
    uid: "04498af32898437bb72bbba9b74d",
    picUrl: "https://randomuser.me/api/portraits/men/12.jpg",
    firstName: "Andrew",
    lastName: "Carter",
    city: "Seattle",
    state: "WA",
    preferredCodingTime: ["afternoon"],
    frontendTechStack: ["HTML", "CSS", "Javascript"],
    backendTechStack: ["Linux", "Nginx"],
    specialty: ["Back-End"],
    preferredTechStack: [
      "Java",
      "Angular",
      "Linux",
      "Apache",
      "MySQL",
      "PHP",
      "MongoDB",
    ],
    bio:
      "Amet purus gravida quis blandit turpis. Amet commodo nulla facilisi nullam.",
  },
  {
    uid: "39a696ec2dae49f9885fe5b1f0b9",
    picUrl: "https://randomuser.me/api/portraits/women/14.jpg",
    firstName: "Joyce",
    lastName: "Harvey",
    city: "Manhattan",
    state: "NY ",
    preferredCodingTime: ["morning"],
    frontendTechStack: ["HTML", "CSS", "Vue"],
    backendTechStack: ["Linux", "SQLite", "Rails", "Python", "Nginx"],
    specialty: ["Front-End"],
    preferredTechStack: ["HTML", "CSS", "Javascript", "Vue"],
    bio:
      "Vulputate ut pharetra sit amet aliquam. Odio euismod lacinia at quis risus.",
  },
  {
    uid: "ef54de16b1bc4cde9b9d4dc1eb1b",
    picUrl: "https://randomuser.me/api/portraits/women/20.jpg",
    firstName: "Margaret",
    lastName: "Ortiz",
    city: "Miami",
    state: "FL",
    preferredCodingTime: ["afternoon", "evening"],
    frontendTechStack: ["HTML", "CSS", "React", "Angular", "Vue"],
    backendTechStack: [
      "Express.JS",
      "AngularJS",
      "Node.js",
      "Javascript",
      "Nginx",
    ],
    specialty: ["Back-End"],
    preferredTechStack: [
      "MySQL",
      "PHP",
      "MongoDB",
      "Express.JS",
      "AngularJS",
      "Node.js",
    ],
    bio: "Quam quisque id diam vel quam elementum pulvinar etiam. ",
  },
  {
    uid: "3eed885a378649318ad693ff26fe",
    picUrl: "https://randomuser.me/api/portraits/men/33.jpg",
    firstName: "Matthew",
    lastName: "Lewis",
    city: "Indianapolis",
    state: "IN",
    preferredCodingTime: ["evening"],
    frontendTechStack: ["Javascript", "Angular", "Vue"],
    backendTechStack: ["Linux", "Rails", "Python", "Nginx"],
    specialty: ["Full-Stack"],
    preferredTechStack: [
      "Apache",
      "MySQL",
      "PHP",
      "MongoDB",
      "Express.JS",
      "AngularJS",
      "Node.js",
      "Javascript",
      "Ruby",
    ],
    bio:
      " Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. ",
  },
  {
    uid: "6c6331781c9b46429bee110a3909",
    picUrl: "https://randomuser.me/api/portraits/women/10.jpg",
    firstName: "Susan",
    lastName: "Greene",
    city: "Chicago",
    state: "IL",
    preferredCodingTime: ["afternoon"],
    frontendTechStack: ["Javascript"],
    backendTechStack: ["Python", "Linux", "Nginx"],
    specialty: ["Front-End"],
    preferredTechStack: [
      "HTML",
      "CSS",
      "Angular",
      "Javascript",
      "Ruby",
      "SQLite",
      "Rails",
      "Python",
    ],
    bio: "Ornare suspendisse sed nisi lacus sed.",
  },
  {
    uid: "c95f4d95cb044129b32ca3791d67",
    picUrl: "https://randomuser.me/api/portraits/women/34.jpg",
    firstName: "Debra",
    lastName: "Ford",
    city: "New Orleans",
    state: "LA",
    preferredCodingTime: ["morning", "evening"],
    frontendTechStack: ["Javascript", "jQuery"],
    backendTechStack: ["Express.JS", "AngularJS", "Node.js"],
    specialty: ["Front-End"],
    preferredTechStack: ["HTML", "CSS", "Javascript", "Angular"],
    bio: "coding is my love",
  },
  {
    uid: "0799d94461a74909926f30b955be",
    picUrl: "https://randomuser.me/api/portraits/men/23.jpg",
    firstName: "Ralph",
    lastName: "Ramos",
    city: "Los Angeles",
    state: "CA",
    preferredCodingTime: ["afternoon"],
    frontendTechStack: ["HTML", "CSS", "jQuery", "React"],
    backendTechStack: ["Node.js", "Javascript", "Ruby", "SQLite"],
    specialty: ["Full-Stack"],
    preferredTechStack: [
      "HTML",
      "CSS",
      "Javascript",
      "Angular",
      "Ruby",
      "SQLite",
      "Rails",
      "Java",
    ],
    bio: "Consequat id porta nibh venenatis cras.",
  },
  {
    uid: "059c5bffa91d495b9850a5ea532d",
    picUrl: "https://randomuser.me/api/portraits/women/21.jpg",
    firstName: "Carol",
    lastName: "Woods",
    city: "San Francisco",
    state: "CA",
    preferredCodingTime: ["morning"],
    frontendTechStack: ["Vue"],
    backendTechStack: ["Python", "Linux"],
    specialty: ["Front-End"],
    preferredTechStack: ["HTML", "CSS", "Javascript", "Python"],
    bio:
      "Tincidunt nunc pulvinar sapien et ligula. Donec ac odio tempor orci dapibus ultrices in iaculis.",
  },
];
